import React, { useEffect, useState } from 'react';
import { useSelector } from 'react-redux';
import { RiseLoader } from 'react-spinners';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faDownload } from '@fortawesome/free-solid-svg-icons';
import { handleDownload } from './downloadImage';
import { ToastContainer } from 'react-toastify';

const FooocusModel = ({ userInput, negativePrompt }) => {
  const { fooocusResult, isLoading } = useSelector((state) => state.fooocusImage);
  const [imageBlob, setImageBlob] = useState(null);

  useEffect(() => {
    if (fooocusResult && fooocusResult.images && fooocusResult.images[0] && fooocusResult.images[0].url) {
      const imageUrl = fooocusResult.images[0].url;
    

      fetch(imageUrl)
        .then(response => {
          if (!response.ok) throw new Error('Network response was not ok');
          return response.blob();
        })
        .then(blob => {
          const blobUrl = URL.createObjectURL(blob);
          setImageBlob(blobUrl);
        })
        .catch(error => console.error('Error fetching the image:', error));
    }
  }, [fooocusResult]);

  const downloadImage = () => {
    if (imageBlob) {
      handleDownload(imageBlob, 'fooocus-image.jpeg');
    }
  };

  return (
    <div>
      <ToastContainer position="top-center" />
      {isLoading ? (
        <div className="loader-container">
          <RiseLoader color="#08bbd3"/>
        </div>
      ) : (
        imageBlob && (
          <div className="image-downloadable" onClick={downloadImage}>
            <img src={imageBlob} alt="Generated by Fooocus" className="responsive-image" />
            <div className="download-icon">
              <FontAwesomeIcon icon={faDownload} />
            </div>
          </div>
        )
      )}
    </div>
  );
};

export default FooocusModel;
